### ISSUE TITLE
Write specification of on chain fork detection protocol

### ISSUE THREAD

**Issue by melekes** [tendermint/spec#104]
We need to write precise specification of execution of fork detection protocol on chain. This includes interaction with a lite client (once lite client detects a fork), evidence creation, gossiping of evidence, committing evidence as part of block, and then evidence processing as part of block execution. The specification should define precisely various terms (fork, slashable fork, evidence, height vote set as part of challenge response, etc) and also contain diagram of interactions between various parties.

_(the issue was moved from https://github.com/tendermint/tendermint/issues/4217)_

**Comment by josef-widder** [comment]
Here is the doc that gives an overview over several documents and issues: https://docs.google.com/document/d/1LMVUrdZ6r2G_gD9Yc8nr4RC-SEkgYYPR3DAKSdFdY7M/edit?ts=5eff62aa#heading=h.qlzor1kzfmon
