### ISSUE TITLE
spec: evidence reactor

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#110]
The spec for the evidence reactor is missing. This is a small reactor and does not do much but to keep consistency we should write a spec for it. This will help if other clients want to do an implementation.

**Comment by marbar3778** [comment]
Only messages and the channelID is needed. This is being done in conjunction with the removal of the reactor section. Closing this issue

**Comment by tessr** [comment]
Will we need an evidence reactor section in the go-tendermint docs?

**Comment by marbar3778** [comment]
Yes, started on that today. As I'm removing things from the spec repo I'm adding them to the Tendermint repo, if they are applicable.
