### ISSUE TITLE
Repo cleanup and polish

### ISSUE THREAD

**Issue by ebuchman** [tendermint/spec#121]
This repo is in a bit of a mixed and under maintained state.

It originally started as a home for the "Latest Gossip on BFT"  paper about the core Tendermint consensus algorithm.

It still houses that paper, and it's Github Releases are about that paper. 

But it is also now home to the [Tendermint Block and P2P Protocol Specs](./spec) and to the spec's RFC process.

We'd like it to be the canonical place for the Tendermint specification and for governance over changes to that spec.

We should:
- Update the README to summarize the state of the repo, the state of implementations, and how to contribute
- Establish spec versioning procedure. Releases of the repo should be about the full spec, not that consensus paper. We should have versioned releases of the spec and it should correspond to the Block Protocol and P2P Protocol versions in Tendermint Core - see https://github.com/tendermint/tendermint/blob/master/version/version.go#L31. What those versions cover / mean should be better described in this repo as well.
- Update details of the RFC process and decision making for breaking changes to the protocol

**Comment by cmwaters** [comment]
Closing this since we're migrating the spec back into the Tendermint repo. Also many of the bullet points here have been addressed i.g. making the rfc process clear.
