### ISSUE TITLE
light client: coordinate exposed API

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#163]
Light client implementations should coordinate exposed API's.

This way users will not have to implement the communication separately. 

Currently, the go implementation shares the same API as the RPC layer. I believe this is a good approach and if its adopted as the light client spec API we should form an RPC API spec within this repo. 

Things to note about this discussion:

- Tendermint-go had a conversation around migrating to gRPC
  - This conversation may need to be moved into this repo if clients will share API's. Although we could keep the RPC layer as is and clients could add a layer like gRPC as a feature of their client if they see it necessary or useful.

**Comment by cmwaters** [comment]
I think we can close this. The API's in term of the RPC endpoints are aligned and there aren't any conversations currently of changing that
