### ISSUE TITLE
Add Vote to BeginBlock

### ISSUE THREAD

**Issue by folex** [tendermint/spec#192]
Hi! I'm working at FluenceLabs, and we're using Tendermint as a consensus engine to provide trusted execution environment for user applications. 

### In short
We upload Tendermint blocks to decentralized storage, and need to reconstruct blocks inside ABCI app from info from `BeginBlock` and `DeliverTx`. But we're signatures from `Vote`s since `VoteInfo` contains only a boolean flag and validator address.

#### Background
In addition to security guarantees given by Tendermint, we also add execution verification to detect Byzantine takeovers. It is essentially a delayed replay of all blocks and transactions, followed by a check that state produced by the Tendermint cluster equals to the state after delayed verification.

To be able to perform delayed verification, we aim to store Tendermint-produced blocks in a decentralized storage like Swarm or Filecoin, so verifiers (fishermen, essentially) are guaranteed to have access to all transaction history. 

#### The problem
To upload a block, we first need to collect it from Tendermint. This is currently done via RPC (both HTTP and Websocket). But there's a problem with collecting blocks only through RPC: it is not available during block replay (after Tendermint node restart). 

The reason this is a problem is that to guarantee all blocks are indeed stored in the decentralized storage, each block must include a storage link to the previous block. **So the block N could be committed only after block N-1 is uploaded.** Currently, our ABCI app waits in `commit` of block N until there's a storage link available for block N-1.

Because of that dependency the following is possible:
1. Block `N-1` was produced, committed, retrieved via RPC and started uploading
2. Tendermint has started block `N` (upload for `N-1` isn't finished yet)
3. Tendermint restarts (e.g., because system is rebooted), and block replay begins
4. ABCI app `commit` for block `N` hangs until there's a receipt for block `N-1`
5. RPC isn't available during replay, so the system can't proceed since block `N-1` isn't available

#### Solution
Currently we solve this problem with a dirty hack – we read blocks directly from `blockstore.db`. This is fragile since it is not a part of public Tendermint API, and overall a bad solution.

There are two possible solutions for that: 
1. Reconstruct blocks inside ABCI app
2. Make RPC available during block replay. 

After discussing that with members of Tendermint Core team in person, we decided to go with the former solution. And the only pieces of information that are lacking are validator's signatures encoded in `Vote` structure.

### Implementation
I will provide a PR that adds `Vote` to `VoteInfo` shortly, and would be glad to discuss all the details, and would be grateful to get some help and advice with that.

Here it is tendermint/tendermint#3957

**Comment by cmwaters** [comment]
Update on this issue: We are in the process of changing the ABCI API. One part of this change is delivering the entire block instead of in pieces. Refer to the [spec](https://github.com/tendermint/tendermint/blob/325740a57c18b30cb4e56d1d80ebbcad4a0b339d/spec/abci++/README.md) for more details. I'm going to mark this issue as resolved unless anyone has any disputes.
