### ISSUE TITLE
Add block pre-processing phase

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/spec#194]
Many significant scalability improvements require a pre-processing phase from the proposer in creating the block, and all other nodes to have a way to verify the results. Two use cases that immediately come to mind are for state-machines which want to combine all BLS signatures for the block as a whole, and state-machines that want the proposer to condense all txs into a series of state transitions and a single stark proof that every state transition is correct. We absolutely need to support state machines doing both of these things. 

My proposal is to create the following ABCI process:
* `PreProcessTxs(Txs) Txs` - Proposer gives state machine the set of txs as a whole. State machine processes txs, and returns an array of processed txs. The BLS use-case would then basically be making a new "BLS multi-msg" type, and a tx on that. This similarly works for the STARK use case. Now you can re-use the existing CheckTx / DeliverTx processes with these. 

I would like to try to get this in v1.0 if anyone else agrees. From conversations with @sunnya97, other people building on the SDK want this as well. (They are currently doing a hacky thing where they punted all verification / delivering work to EndBlock, clearly not what we want to be doing)

**Comment by ValarDragon** [comment]
I suggest amending `preprocess_block` to `preprocess_proposal`. The difference is that `preprocess_proposal` would allow processing on the commit as well, which would enable optimizations like aggregating precommit signatures.

**Comment by ValarDragon** [comment]
I suggest that we change `PreprocessTxs` to `PreprocessProposal`. 

Recall that a block proposal for block N+1 contains `txs for block N + 1, Commit for block N`. 

This would change the API from roughly `PreprocessTxs([] Input Tx Type) -> [] Output Tx Type` to instead `PreprocessProposal([] Input Tx Type, LastCommit) -> [] Output Tx Type, ProcessedCommit`. 

This enables aggregate signatures as defined by the application, but it actually enables much more! In issue <X>, we suggest having the application allow per-validator data be included in their precommit (similar to BFT time). This becomes very useful in tandem with that. In the case of threshold decryption shares, it 100x reduces the p2p overheads to full nodes due to aggregation.

This causes the following further change. The ProcessedCommit should be a struct of `{ tx hash, height, round, signer_bitmap, app_data, verification_data}`. (The BFT time would be in the app_data)

Tendermint will be responsible for checking the `tx hash, height, round, signer_bitmap` relationship. We would then need a new ABCI method called `VerifyProcessedCommit`, with the following type signature `VerifyProcessedCommit( Processed Commit) -> Bool`. 

This nicely enables aggregate signatures to be something defined by and handled within the application, in addition to allowing better aggregation for precommit extensions.

**Comment by cmwaters** [comment]
This proposal is being implemented as part of the ABCI++ work. Refer to this part in the [spec](https://github.com/tendermint/tendermint/blob/be83ec6664ecfc974f92006db7932249c5f80c93/spec/abci++/abci++_methods_002_draft.md) for more context.
