### ISSUE TITLE
abci: Allow applications to process transactions in batch

### ISSUE THREAD

**Issue by danil-lashin** [tendermint/spec#195]
### Problem

Developers cannot optimize transaction processing in applications because they receive one tx per time.

For example, the most expensive part of tx execution is public key derivation (ECDSA) from tx's signature. Derivation can be done in parallel and this approach will give us several times speed-up. 

And also many kinds of applications can process transactions simultaneously. 

### Solution

Allow applications to process transactions in batch.

I've started some work here: https://github.com/danil-lashin/tendermint/commit/370a0850a0845b94f3f1a8f35dee04a2791abbfd. If you agree with this approach, I will be happy to make a complete PR.

**Comment by cmwaters** [comment]
The team have decided to integrate this proposal into the new ABCI++ feature set. More information on the actual implementation can be found in the [spec](https://github.com/tendermint/tendermint/blob/6280f4546010d285222c345253fcc37f7e1aab4b/spec/abci++/abci++_methods_002_draft.md).
