### ISSUE TITLE
ABCI: add CheckBlock into Application to allow app checking block before prevote

### ISSUE THREAD

**Issue by cjqpker** [tendermint/spec#197]
In below senarios we may need this feature:

1、We don't allow invalid txs included in each block so we need to run block before prevote , the same way as btc and ethereum

2、Our app need to support sharding modules and each sharding module has it's own stateroot respectively so we need to check sharding state root hash in application

**Comment by cmwaters** [comment]
We are in the process of implementing a version of this in the upcoming ABCI changes. The new method, `ProcessProposal` allows for applications to verify a block before prevoting. More details can be found in the [spec](https://github.com/tendermint/tendermint/blob/325740a57c18b30cb4e56d1d80ebbcad4a0b339d/spec/abci++/README.md)
