### ISSUE TITLE
Investigate QUIC and the unreliable datagram extension for peer to peer

### ISSUE THREAD

**Issue by zmanian** [tendermint/spec#198]
The IETF QUIC (a UDP based protocol which combines some characteristics of connections and TLS) is also potentially having datagram semantics.

It also includes a datagram semantics over the same connection.

This will eliminate RTT overhead on sending votes to peers.
https://datatracker.ietf.org/doc/draft-pauly-quic-datagram/?include_text=1

**Comment by cmwaters** [comment]
QUIC is being considered as part of the LibP2P migration so I think it's fine to close this issue. More information can be found in this [ADR](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-073-libp2p.md)
