### ISSUE TITLE
Batches for Ordering vs Blocks for Verifiability

### ISSUE THREAD

**Issue by ebuchman** [tendermint/spec#2]
FROM @milosevic:

I was going through the documentation at https://tendermint.readthedocs.io (great work), and have few comments/questions on the general architecture/design decisions. In general, my starting point is general BFT replication, and then I am trying to understand what is new or different in the context of blockchain application. Sorry for saying here general things, it's just for completeness. 

As a very big picture, in pure BFT, we have a deterministic service S that is being replicated onto N replicas. At most f out of this N replicas can be faulty. 
Clients send requests (we can also call it transactions) to replicas (there are different schemas, but for simplicity lets say to a subset of replica), and then wait to receive the corresponding matching replies from at least f+1 replicas. Once they receive matching replies from at least f+1 replicas, they consider reply as valid. Replicas run consensus protocol to agree on the order in which requests will be executed. As replicated logs managed by the replicas can grow infinitely, replicas normally take periodic state checkpoints (snapshot), and prune logs up to the snapshot point. In case of slow replicas, or adding new replicas to the system, requests are normally replayed starting from the latest committed state. In this model, clients don't care about application state, consensus protocol or checkpointing protocol. They care only about maximum number of faulty replicas f, and about replica set. In case of what I called here pure BFT, there are no notion of blocks, requests are simply totally ordered. As a frequent optimisation consensus protocol is run not for a single request, but for a batch of requests. This is optimisation that is completely hidden from the client and very frequently also from the application that is being replicated.

In my understanding what we have as a new requirement with blockchain applications is verifiability, i.e., a possibility for a client to verify the state of the application and potentially whole transaction history. In case of PoW blockchain systems, linking of blocks of transactions into chain is the core ordering (consensus) mechanism. It is then also used by client to verify application state. Therefore, the concept of block and linking of blocks has two roles: 1) ordering and 2) verifiability.

In case of PoS blockchain systems, order of blocks is defined by the consensus protocol. Guarantees come from the assumptions that number of faulty replicas have at most f voting power. The role of block and linking of blocks is therefore in my view quite different, i.e., it has only to deal with verifiability as ordering comes from the consensus. In my understanding, if we would have replicas just sign exactly the same block of transactions in a sequence, that would be from the security point of view exactly the same. With PoS architecture, the role of consensus is just to have replicas agree what will be the content of block 1, block 2, etc. Note that with this reasoning, it might be possible to even more split ordering part from the blockchain/application part. If we could have replicated log of transactions, then we could from this log using some deterministic rule create blocks of transactions, chain them and sign it. You can then imagine various design options, for example, replicated log can be push based (like in Tendermint) where log is pushing transaction to the application, or pull based (like in Kafka) where application can read transactions from the log in the order. I am wondering if in the case we split ordering from the blockchain part, verifiability of blockchain and application state in general, could be simpler, i.e., could it be enough just to receive block commit messages from replicas that have more than f voting power?

In general, whole verifiability aspect and chaining of blocks is still not very clear to me in Tendermint and some aspects are less clean compared to the rest. For example, block message for height H contains LastCommit from height H-1. In my understanding this comes from the fact that the content of the next block for height X is fixed at the beginning of the round of the consensus instance X. At this point we only know LastCommit of instance X-1, so clearly, we cannot do better. If it would be possible to first order transactions, and then commit and sign the next block, the block could contain its proof, i.e, the block would be more self-contained. 

With the current approach, we also mix concerns, as batch of transactions in consensus is the same as a block of transactions in the blockchain. As these are different concepts and potentially have different optimal values, maybe having different values for these two concepts might be more appropriate in a particular network setup. 

Sorry for going a bit off-road with this discussion, my goal is just to try to understand better verifiability aspect as I think it would be useful to have it formally defined in the spec document.

**Comment by ebuchman** [comment]
> if we would have replicas just sign exactly the same block of transactions in a sequence, that would be from the security point of view exactly the same

Maybe. But I think it means we'd need another rule that you can only propose block X once you have block X-1, and there's no way to check that (at least a hash is an integrity check). If we're using an application without a state root, the last block hash would be the integrity check. If you have a state root in every block, then the blocks are implicitly linked via their state roots (ie. you have to have the transactions from X-1 to compute the state root to include in block X), but it might also be possible that some txs dont change the state root, or other fancy rules, so you can't be certain.

I think the block linking serves the same purpose as checkpointing in PBFT. It also provides a natural place to prune old history (ie. some integer number of blocks back). I saw the collapse of "checkpoint" and "commit" into a single "block=batch" as actually an optimization itself, but how that is so could certainly be better worked out - maybe it's actually wrong, or there could be something better, as you're alluding to.

> we also mix concerns, as batch of transactions in consensus is the same as a block of transactions in the blockchain. As these are different concepts and potentially have different optimal values, maybe having different values for these two concepts might be more appropriate in a particular network setup.

I'd love to know more about what you find along this dimension.

> the block would be more self-contained.

This one is annoying. We have to wrestle with off-by-one issues in many places. But it does reduce the overhead in certain paths of the algorithm, because it allows you to only run the txs after you've committed them, instead of potentially wasting time computing the app hash on a block that might not get committed.

**Comment by cmwaters** [comment]
From what I understand, the proposals made here are some what in effect and have been decided on. I'm not sure if this issue still has a purpose and I'm going to close this unless someone disagrees
