### ISSUE TITLE
⟨PROPOSAL, hp, roundp, v, r⟩ replace `r` with `vr`? 

### ISSUE THREAD

**Issue by jaekwon** [tendermint/spec#20]
In the current spec, line 29:

`upon ⟨PROPOSAL, hp, roundp, v, r⟩ from proposer(hp, roundp) AND 2f + 1 ⟨PREVOTE, hp, r, id(v)⟩ while step = propose do`

I think this is referring to this:

https://github.com/tendermint/tendermint/blob/2aa2b63cadc42cca1071c36adfd2f2ce14e1aa8f/consensus/state.go#L1583-L1588

```go
		} else if cs.Proposal != nil && 0 <= cs.Proposal.POLRound && cs.Proposal.POLRound == vote.Round {
			// If the proposal is now complete, enter prevote of cs.Round.
			if cs.isProposalComplete() {
				cs.enterPrevote(height, cs.Round)
			}
		}
```

I think it would be less confusing if it were:

`upon ⟨PROPOSAL, hp, roundp, v, vr⟩ from proposer(hp, roundp) AND 2f + 1 ⟨PREVOTE, hp, vr, id(v)⟩ while step = propose do`

I just think that calling anything `r` which isn't `roundp` is confusing, esp cuz `r` is generally used to refer to `roundp` (I think).  E.g.:

> The validValue and validRound are updated to v and r by a correct process in a round r when the process receives valid PROPOSAL message for the value v and the corresponding 2f + 1 PREVOTE messages for id(v) in the round r (see the rule at line 36).

So suggested example modification:

> A correct process p accepts the proposal for a value v (send PREVOTE for id(v)) if an external valid function returns true for the value v, and if p hasn’t locked any value (lockedRound = −1) or p has locked the value v (lockedV alue = v); see the line 26. In case the proposed pair is (v, r) and a correct process p has locked some other value (v′ ̸= v), it will accept v only if v′ was more recent possible decision value8 in the round higher than lockedRoundp (r > lockedV aluep).

I think could be reworded as:

> A correct process p accepts the proposal for a value v (send PREVOTE for id(v)) if an external valid function returns true for the value v, and if p hasn’t locked any value (lockedRound = −1) or p has locked the value v (lockedValue = v) **AND we have +2/3 prevotes for round vr or later**; see the line 26. [SECOND SENTENCE REMOVED]

**Comment by milosevic** [comment]
Fixed in https://github.com/tendermint/spec/pull/34.
