### ISSUE TITLE
abci: fill block with app defined txs

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#201]
# Protocol Change Proposal

## Summary

The mempool decides how to fill blocks, in the Tendermint-Go implementation this is based on a FIFO list. There has been discussion to add a priority field to `CheckTX` and handle sorting on the Tendermint side (https://github.com/tendermint/spec/issues/162). 

## Problem Definition

With Tendermint handling sorting the Application and Tendermint boundary will begin to blur. This will lead to greater complexity. 

## Proposal

If `tx_id` were to be added to transactions and CheckTx (https://github.com/tendermint/spec/issues/191) a new method for the mempool ABCI connection could be created that requests a list of `tx_id`s from the application and tendermint picks these txs from the mempool, if the app does not care which transactions to include in a block, Tendermint would fallback to the FIFO method.

```proto
message RequestTxs {
	height = 1;
}

message ResponseTxs {
	repeated tx_keys = 1;
}
```

This would negate the need for sorting of the mempool in Tendermint.  

### Concern

This could lead to duplication of data across the application and Tendermint. A simple way to negate this concern is that the app only keeps knowledge of the key (id) and not the value (data)

**Comment by marbar3778** [comment]
Another concern brought up by @erikgrinaker is how to handle mempool eviction if the proposal were to be moved forward. If the transactions are stored by tx_id Tendermint will not know when its time to evict transations. With a priority field in `ResponseCheckTx` Tendermint can make the assumption that the txs with the lowest priority can be evicted.

**Comment by cmwaters** [comment]
I think the `PrepareProposal` method gives the application sufficient opportunity to add their own transactions. There have also been discussions [here](https://github.com/tendermint/tendermint/issues/7663) around transaction tracing and mempool garbage collection. I'm going to close this issue but feel free to reopen if you think there are extra details of importance here.
