### ISSUE TITLE
Spec versioning

### ISSUE THREAD

**Issue by tessr** [tendermint/spec#204]
There's been a lot of discussion about whether the spec should have version numbers, so that different implementations can reference particular versions of the spec. This is probably blocked on getting the Rust/Go specs reunified, and there are other open questions as well:

* Does this mean we'll start doing releases for specs? 
* What versioning convention should we follow? If semver, what constitutes a major vs. minor change? 

There are probably other unanswered questions or tradeoffs, but this is what I can think of for now.

**Comment by erikgrinaker** [comment]
>Does this mean we'll start doing releases for specs?

My vote is yes. And all versions should be available in rendered form on the web somewhere. Stuff like showing diffs between versions would be awesome for integrators and implementers.

> If semver, what constitutes a major vs. minor change?

I'd say we follow in the spirit of semver, i.e. a major version breaks stuff (e.g. removes a message), minor version adds stuff (e.g. an additional field that defaults to the old behavior and degrades gracefully), and patch versions fix stuff (e.g. a typo or an additional explanatory paragraph).

**Comment by josef-widder** [comment]
At informal we have started a versioning scheme for specs. We use numbers and "state" of a spec. For instance, for the light client verification, we have `verification_001_published.md` (which means thoroughly reviewed, discussed, and deemed "official") and [`verification_002_draft.md`](https://github.com/tendermint/spec/blob/master/rust-spec/lightclient/verification/verification_002_draft.md) which contains some updates, that are still underway. 

Within the spec we extensively we use tags to highlight also versioning for specific functions within the spec. For instance [[LCV-FUNC-MAIN.2]](https://github.com/tendermint/spec/blob/master/rust-spec/lightclient/verification/verification_002_draft.md#lcv-func-main2) shows that there is a difference to the function definition [LCV-FUNC-MAIN.1] while unchanged functions maintain their old version number
