### ISSUE TITLE
Define "acceptable"

### ISSUE THREAD

**Issue by jaekwon** [tendermint/spec#21]
> First thing to note is that at the beginning of every round during the system execution there is at least single correct process c such that validValuec and validRoundc are **acceptable** by every correct process. This is true as at there exists a correct process c such that for every other correct process p, validRoundc > lockedRoundp or validValuec = lockedValuep. This is true as c is the process that has locked value in the most recent round among all correct processes (or no correct process locked any value).

Do we need to define "acceptable"?

**Comment by milosevic** [comment]
Fixed in https://github.com/tendermint/spec/pull/34.
