### ISSUE TITLE
Write a TLA+ specification for evidence handling

### ISSUE THREAD

**Issue by konnov** [tendermint/spec#226]
Following PR #225, we are going to:

 - [x] Revive the [tendermint specification](https://github.com/informalsystems/tendermint-rs/tree/master/docs/spec/tendermint-fork-cases) for fork accountability
 - [x] Write a high-level specification for the function `[FN-FUNC-MAIN.1]`, which is called `isolateMisbehavingProcesses` in the Golang pseudo-code.
 - [x] Finish Part V of #225
 - [x] Run the complete set of experiments

To write the spec for `[FN-FUNC-MAIN.1]` we have to extend the commit structure in the Blockchain model as explained in [verification_002_draft.md](https://github.com/tendermint/spec/blob/master/rust-spec/lightclient/verification/verification_002_draft.md#tmbc-vote1).

**Comment by josef-widder** [comment]
https://github.com/tendermint/spec/pull/232
