### ISSUE TITLE
Variable block header

### ISSUE THREAD

**Issue by hammadtq** [tendermint/spec#236]
# Protocol Change Proposal

## Summary

Block header needs to be flexible and should allow developers to add/change their own fields when necessary.

## Problem Definition

In our use-case we are implementing a privacy protocol called quisquis and the block header would need to change to incorporate Utreexo for state snapshot as well as state header for sparse merkle tree (of commitments). If we were to change the header at this stage, it seems like we will have to fork the tendermint and add our fields in the header. 

 By incorporating this change, other teams working on tendermint would also be able to use tendermint as it is rather than forking and going with their own version.

I see no disadvantages of this approach as we will just be making header fields variable rather than of fixed length etc.

## Proposal

The header fields should be made variable instead of fixed length and fields as described above.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
#194 could be implemented in a way that would allow developers to write arbitrary data into the header and into block data. It would require that the header, as well as the Block in (e.g. in Block.Data), would add an extra field that could be filled with app defined data. The preprocess step could be used to fill the fields by the app. This will likely be sufficient for your use-case I guess. Unless, for your use-case, the data wouldn't just be opaque blobs from the point of view of tendermint but instead tendermint would need to understand the data (and not only the app) because then you would have to fork despite the additional fields.

Another, much more radical (and way more complex) approach would be to abstract away the fields entirely and make header an interface/trait. My understanding is that this would be unlikely to land in go-tendermint.

**Comment by cmwaters** [comment]
Zooming out a little further, I believe the key advantage with variable headers is that it could make Tendermint more generalisable and with greater flexibility to the application's specific use case. This is something that an application-centric consensus engine probably wants to aim for but then must be also wary of the risk or tradeoff of trying to spread itself too broadly. 

The neat advantage is that in Tendermint, the header is always the first data structure that is verified. The header with all its hashes is then capable of verifying other secondary data structures such as the Tx block, the evidence, the last commit, or tx results. Giving the application access to the header means that it can choose between what is primary level data and what is secondary level data allowing it to have very lean headers if it doesn't require many of the additional features that Tendermint offers or very large headers if it wants to extend some of the features over and above what Tendermint currently offers.

I believe the main hesitation in moving forward with something like this is a matter of separation of concern. Already, the line between what the application should handle and what is expected of Tendermint to handle is blurred. Splitting the header between what is core to Tendermint verification and what the application wants definitely disrupts this notion of a clean divide between state machine replication engine and the application layer on top of it.

**Comment by hxrts** [comment]
This is still a desirable feature for several projects.

**Comment by cmwaters** [comment]
Sorry about that. It seems our stale bot when crazy after the last update and has decided to close issues as well as PR's. I will open a PR to fix it.

**Comment by marbar3778** [comment]
In yesterdays call we discussed the header and where such data could live. 

There were two designs discussed. First a hash of the data is stored in the header, but the data is stored else where in the block, either in the data field or a new field. 

``` 
message Block {
  Header                        header      = 1 [(gogoproto.nullable) = false];
  Data                          data        = 2 [(gogoproto.nullable) = false];
  tendermint.types.EvidenceList evidence    = 3 [(gogoproto.nullable) = false];
  Commit                        last_commit = 4;
 repeated byte app_data = 5;
}
```

or 

```
// Data contains the set of transactions included in the block
message Data {
  // Txs that will be applied by state @ block.Height+1.
  // NOTE: not all txs here are valid.  We're just agreeing on the order first.
  // This means that block.AppHash does not include these txs.
  repeated bytes txs = 1;
 repeated bytes app _ data = 2;
}
```

The second design is the proposed design in abci++:

```

// Header defines the structure of a Tendermint block header.
message Header {
  // basic block info
  tendermint.version.Consensus version  = 1 [(gogoproto.nullable) = false];
  string                       chain_id = 2 [(gogoproto.customname) = "ChainID"];
  int64                        height   = 3;
  google.protobuf.Timestamp    time     = 4 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];

  // prev block info
  BlockID last_block_id = 5 [(gogoproto.nullable) = false];

  // hashes of block data
  bytes last_commit_hash = 6;  // commit from validators from the last block
  bytes data_hash        = 7;  // transactions

  // hashes from the app output from the prev block
  bytes validators_hash      = 8;   // validators for the current block
  bytes next_validators_hash = 9;   // validators for the next block
  bytes consensus_hash       = 10;  // consensus params for current block
  bytes app_hash             = 11;  // state after txs from the previous block
  bytes last_results_hash    = 12;  // root hash of all results from the txs from the previous block

  // consensus info
  bytes evidence_hash    = 13;  // evidence included in the block
  bytes proposer_address = 14;  // original proposer of the block
 repeated bytes app_data = 15;
}
```

The tendermint team is leaning towards one of the variations of the first proposal. @hammadtq which would be preferred by you?

**Comment by cmwaters** [comment]
Just FYI, Tendermint doesn't check the length of the app hash only the other hashes that it has control of. It would be possible to include multiple hashes or any other arbitrary data in the header. There might be complications with block size as we treat headers as having a fixed size when allocating how many transactions can fit in a block. I'm going to close this issue. Feel free to open it up again (or on the `tendermint/tendermint` repo) if you thing there's something here still outstanding.
