### ISSUE TITLE
Move "reactors" out of spec

### ISSUE THREAD

**Issue by tessr** [tendermint/spec#238]
We currently have a directory for "reactors" under "spec." Reactors are implementation-specific, and we should move documentation on reactors out of this repo and into tendermint/tendermint. (I think.) 

/cc @marbar3778

**Comment by alexanderbez** [comment]
Makes sense to me!

**Comment by marbar3778** [comment]
Makes sense to me. We only need to keep the p2p message documentation and channelIDs within the spec.

**Comment by cmwaters** [comment]
This has already been done right? We can close this issue?
