### ISSUE TITLE
ci: action to open issues in tm-go & tm-rs

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#255]
Look into creating a github action that would open issues in the tendermint and tendermint-go repos when a spec breaking change has occurred. 

This action would be used only when a spec breaking change has occurred. Not when an RFC for a potential breaking change has been merged.

**Comment by cmwaters** [comment]
Could be a nice idea. Would this happen whenever a PR is merged into master? Would someone have to add a label?

**Comment by marbar3778** [comment]
Yea we would add a label for specific PRs. I am imagining opening the Issue with the description of the PR and a link to the PR.
