### ISSUE TITLE
broken links in docs

### ISSUE THREAD

**Issue by hxrts** [tendermint/spec#257]
# Protocol Change Proposal

## Summary

Looks like a bunch of the links [here](https://github.com/tendermint/spec/tree/master/spec#p2p-and-network-protocols) are broken

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alessio** [comment]
I stumbled across a broken link while browsing this page. Particularly, the dangling link is peer exchange [(PEX) reactor doc (opens new window)](https://github.com/tendermint/spec/blob/master/spec/reactors/pex/pex.md).

That URL seems to refer to the file `spec/reactors/pex/pex.md` that was remove in this PR authored by @marbar3778: https://github.com/tendermint/spec/pull/242

Hope this helps.
