### ISSUE TITLE
spec: define an RPC spec

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#273]
## Summary

Write a spec for the JSON RPC. As another client is beginning we should specify the JSON RPC so that both clients have something to implement against instead of going off of what tendermint-go does. 
____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by josef-widder** [comment]
Does that mean we should define the remote procedures offered by full nodes? 

If yes, It would also make sense to define the other side, that is, how the client should use RPC in a robust way. Typically, clients might run under the assumption that the full node on the other side may be faulty, so some basic checks on whether the return values (and error codes) make sense given the inputs should be codified.

**Comment by marbar3778** [comment]
> Does that mean we should define the remote procedures offered by full nodes?
> 
> If yes, It would also make sense to define the other side, that is, how the client should use RPC in a robust way. Typically, clients might run under the assumption that the full node on the other side may be faulty, so some basic checks on whether the return values (and error codes) make sense given the inputs should be codified.

yes, this would be correct. I am a bit wary of diving into how clients should use the RPC, this can be a rabbit hole and could restrict the usage leading to more questions. As a start we should at least have the RPC API defined.

**Comment by josef-widder** [comment]
Perhaps we do not need to spec out what the clients should do. Still, the only reason why we do e.g., light client verification and detection is that the full nodes might respond to RPCs totally different of what we are going to write in these RPC specifications (e.g., return wrong headers). In particular, we should make clear that a full node can try to launch an attack by not following this specification.

Just specifying the lucky path without at least a disclaimer might lure client designers into the trap of trusting any information returned by an RPC.

**Comment by marbar3778** [comment]
> Perhaps we do not need to spec out what the clients should do. Still, the only reason why we do e.g., light client verification and detection is that the full nodes might respond to RPCs totally different of what we are going to write in these RPC specifications (e.g., return wrong headers). In particular, we should make clear that a full node can try to launch an attack by not following this specification.
> 
> Just specifying the lucky path without at least a disclaimer might lure client designers into the trap of trusting any information returned by an RPC.

I don't follow how someone could attack the network via the RPC? If the light client connects to an RPC that is sending unspecified messages it would not be able to process the messages.

This was meant to be an issue to build something like https://eth.wiki/json-rpc/API

**Comment by josef-widder** [comment]
No, vice versa. The client could be attacked by a faulty full node. 

If the the lightclient asks for a header of height 5 and the adversarial full node returns with a header of height 6, this message could be processed. But if the client is not prepared for this it might generate problems in the client's state.

My point is just that in an adversarial setting, just describing the lucky path might give the wrong impression. We should raise the awareness. That's all.

**Comment by marbar3778** [comment]
> No, vice versa. The client could be attacked by a faulty full node.
> 
> If the the lightclient asks for a header of height 5 and the adversarial full node returns with a header of height 6, this message could be processed. But if the client is not prepared for this it might generate problems in the client's state.
> 
> My point is just that in an adversarial setting, just describing the lucky path might give the wrong impression. We should raise the awareness. That's all.

ohhhh okay. Didn't see it like that. I can put a disclaimer that it is up to the client to pick a trustworthy node to connect to. This is out of scope of what we can gurentee.
