### ISSUE TITLE
Light client in Go initialization

### ISSUE THREAD

**Issue by josef-widder** [tendermint/spec#293]
Surfaced from [Informal Systems](https://informal.systems/) Evidence end-to-end audit of https://github.com/tendermint/tendermint/commit/5a39f72aa8288696d7284e56e3f630ab721a9f9a.

The initialization logic of the lightnode in the Go implementation differs significantly from the initialization that is specified in the supervisor specification. Here is a list of features that should be documented in an "implementation-specific" specifications that focus on the features of the Go implementation of the light client

- [Trustoptions](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/client.go#L148) are used to set trusting period and to point into the initial lightstore to signal that the user trusts that header.
  
- if initialized with a header hash it does [cross check with witnesses](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/client.go#L983). A faulty witness, may prevent the lightnode to initialize. As a result this check was not included in the [specification](https://github.com/tendermint/spec/blob/master/spec/light-client/supervisor/supervisor_001_draft.md#lc-func-init1)

- [latesttrustedblock](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/client.go#L123). II guess for performance reasons it is stored explicitly. It needs to be maintained explicitly.
  

- More generally, the [initialization](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/client.go#L264) based on `options.Height` a bit unclear. This is capturing a unclear case distinction where on initialization "options" is pointing into the lightstore. We should document initialization conditions. What is the initialization supposed to do with respect to an existing lightstore?

**Comment by cmwaters** [comment]
Hey @josef-widder, I would like to write a section on initialisation - specifically how this works when the light clients trusted store is not empty. Can you point to where I should add a piece on such logic. 

> if initialized with a header hash it does cross check with witnesses. A faulty witness, may prevent the lightnode to initialize. As a result this check was not included in the specification

I think we should make the explicit check that all nodes must initially agree on the same block and that that aligns with the trusted block. If a faulty witness wants to prevent the node to initialize, I feel it's better that the operator sees this immediately and can remove that witness if they choose rather than having to deal with it at some later point. It also provides a liveness check.

**Comment by josef-widder** [comment]
As far as I understand the Go implementation deviates from the initialization described [here](https://github.com/tendermint/spec/blob/master/spec/light-client/supervisor/supervisor_001_draft.md#lc-func-init1). I would suggest to create a separate document in the same directory and add a link to that new file to the supervisor spec. Perhaps under "Implementation remark" we could say that the go initialization does another protocol, which is described in the new file (with link).
