### ISSUE TITLE
Evidence reactor specification

### ISSUE THREAD

**Issue by josef-widder** [tendermint/spec#295]
Surfaced from [Informal Systems](https://informal.systems/) Evidence end-to-end audit of https://github.com/tendermint/tendermint/commit/5a39f72aa8288696d7284e56e3f630ab721a9f9a.

The code of the evidence reactor code does not mention any design documents that were used to document the underlying protocol. We thus consider this protocol under-specified. We propose to document the functionality of the evidence reactor. In the following we highlight some points that seemed important to discuss.

### Evidence Pool

General comments on [pool.go](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/pool.go)

- Relationships between the functions (what calls what, who is responsible) for what checks are unclear.

- the context in which this code runs is unclear. Following [comments in the code](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L35) it seems that it is possible that the node is not synchronized. In this case several checks become imprecise.

- invariants on data is only implicit

### AddEvidence

The responsibility of the function are unclear. 
- In the [comment before the function](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/pool.go#L145) it is claimed that "AddEvidence checks the evidence is valid and adds it to the pool",
- in the [comment](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/pool.go#L149) directly after the start of the function it is claimed that "We have already verified this piece of evidence - no need to do it again",
- several lines later, [verify](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/pool.go#L164) is called.

At the same time, all these verification checks at this point seem to  be optimizations to shield the evidence pool against evidence  that is obviously invalid, because the final verdict about the  evidence is done when the evidence is put into a block and  executed.

### Key

It is unclear how the [key](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/pool.go#L692) is constructed. Why is `height` encoded separately? It seems that the used library ensures that the encoding maintains ordering. Such invariants between keys and data should be made explicit.

### Verify

- what is the role of time in the evidence, and why is evidence [dismissed if time does not match](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L45):
  - calls [verifyDuplicateVote](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L222)
  - why is evidence [dismissed](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L262) if the voting powers do not match?

- the [age check](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L59) seems to be an approximate filter in the case the node is currently syncing. If the node is syncing one still may store too old evidence.

- Similarly, there are some specifics that are considered in the case the node is [syncing](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L39). The broader context is unclear. In this part, it is said that no error is raised because the peer should not be disconnected. What are the conditions when a node should be disconnected?

- The checks for lightclient evidence are a bit unclear
  - [this assignment](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L97) does not seem necessary
  - does [this check](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L100) encode a check for lunatic? For lunatic, the evidence height should always be different from the conflicting header height. So it seems unclear what this check does.

- Verifying the lightclient evidence had been [specified](https://github.com/tendermint/spec/blob/master/spec/light-client/attacks/isolate-attackers_002_reviewed.md). It is unclear how [this code](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L86) corresponds to the specification.
  - the naming of the functions and the control flow deviates significantly.
  - the [check for heights](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L184) is unclear. See the comment above.
  - the [check for matching voting power](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L203) is unclear.

- Why is there [isInvalidHeader](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L303) and [ConflictingHeaderIsInvalid](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/evidence.go#L285)

- [intersection of two commits](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/evidence.go#L258) assumes that commits both signatures are ordered identically. In the specification commits are considered as sets. Can a conflicting block have different order?

- [why sorting validators by voting power?](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/evidence.go#L272)

### Validation

- What are the situations in which verify are called?
  [Here](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/evidence/verify.go#L35) it is mentioned that this can happen during syncing. It is unclear what the function should precisely do if it depends on different contexts (different situations of the block store.)

**Comment by cmwaters** [comment]
To me this issue highlights a struggle I seem to consistently be having which is whether the role of the spec repo is to just document protocol patterns and algorithms that must hold across any Tendermint compliant implementation or whether it should also document implementation unique design patterns. The way keys are constructed is an example of this. Having a unified way to store information isn't important to ensuring safe and live state machine replication across nodes. Someone could fork the tendermint-go implementation and run their own key encoding schema. These details are still important and should be documented somewhere. My question is should they be in the spec repo or the tendermint-go repo? 

I don't mind writing up some sort of specification for how the evidence pool should work (and how it does in tendermint-go) but it also strikes me that we don't have any documentation on how the mempool works or how peer exchange works insofar as a few proto messages. I would find it beneficial for me to get some clarity on this.

@marbar3778 @tessr @josef-widder @milosevic

**Comment by tessr** [comment]
My opinion is that the spec repo should be used for implementation-agnostic decisions (e.g., the specification of the Tendermint _algorithm_ and anything that's necessary to operate it in an implementation-agnostic way). It's also good to have implementation-specific documentation (e.g., we should also have documentation on how the mempool or peer exchange works), but historically that's mostly resided in ADRs. It could probably also live in package-level docs. 

It's not clear to me which of the items listed in this issue necessitate `tendermint/spec` changes, but many of them do seem like they could be handled by inline code comments.

**Comment by josef-widder** [comment]
Perhaps the first step would be to go through my comments from the issue and see which are implementation specific, and which are general, and see what should go in what document. I think I would also put implementation specific documentation here when it concerns specific algorithms chosen. Perhaps as a separate file that also mentions which version of the implementation the spec is referring to?
