### ISSUE TITLE
Version: Cut a version of the spec. 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#307]
## Description

Cut a version of the spec in order to move forward on designs and allow teams to converge on a release

Would people be okay cutting v0.1?

**Comment by cmwaters** [comment]
Yup I think now is as good a time as any; we probably should write something up pertaining to how we do versioning and what version changes mean. Also where would we include the spec version in the go implementation

**Comment by marbar3778** [comment]
> Also where would we include the spec version in the go implementation

The version of Tendermint that implements the spec version will include that version on the docs page.

**Comment by josef-widder** [comment]
What is the granularity of the version, that is, is it per protocol or for all protocols?

**Comment by marbar3778** [comment]
I would advocate for a version for the entire spec. Then if we see a problem with this we can work on a more granular design.

**Comment by marbar3778** [comment]
closing in favor of #316
