### ISSUE TITLE
Gossip block parts rarest first

### ISSUE THREAD

**Issue by ebuchman** [tendermint/spec#309]
When we propagate proposal blocks, we pick parts to send randomly. Instead, we should consider a "rarest first" approach where the rarest pieces on the network are gossiped first. This should improve performance and resiliency. 

See eg. http://conferences.sigcomm.org/imc/2006/papers/p20-legout.pdf

I tried out an implementation last year but didnt see much on the performance improvements. We should revisit again.

**Comment by musalbas** [comment]
There's no need to do this if Tendermint gossips erasure coded block data (https://github.com/celestiaorg/lazyledger-core/pull/434#issuecomment-869149444), as it wouldn't matter which parts you receive, as all parts work towards recovering the full block data.
