### ISSUE TITLE
Can we merge CheckTx and DeliverTx response types

### ISSUE THREAD

**Issue by robert-zaremba** [tendermint/spec#342]
# Protocol Change Proposal

## Summary

In Cosmos SDK are re working the Ante Handlers concept. We rethink the middleware process and interfaces and thinking about merging return types of `DeliverTx` and `CheckTx` into single response type.
Ref: https://github.com/cosmos/cosmos-sdk/pull/9920, https://github.com/cosmos/cosmos-sdk/pull/9920#discussion_r693036734

The type definition for ABCI `ResponseDeliverTx`  and 

## Proposal

We would like to have more opinions:
1.  if the Tendermint Team is planning merging these types
2. if not, then if there is any risk if we will merge it for the middle-ware purpose. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
I tend to agree that these responses are different in the way they are used and should remain distinct. It's worth pointing out that with the new ABCI++ method `FinalizeBlock` we might be changing the way the application returns the events/responses for a transaction anyway
