### ISSUE TITLE
ABCI++ comments that needs to be addressed from https://github.com/tendermint/spec/pull/327

### ISSUE THREAD

**Issue by milosevic** [tendermint/spec#351]
- Logic for `OnTimeoutPropose` needs to be added.
- Explanations for `ReceiveProposal` rules are not correct (https://github.com/tendermint/spec/pull/327/files#r710104159, https://github.com/tendermint/spec/pull/327/files#r710107194).
- We should clarify the semantic of `valid(v)` function, i.e., is it done purely at the Tendermint level (basically block header verification), or we assume it requires also application level checks.
- Why we use `getBlockProposal(txdata)` in v0 and `getUnpreparedBlockProposal(txdata)` in v2: https://github.com/tendermint/spec/pull/327/files#r711591189
- Might be good idea adding note that `PrepareProposal` is adding latency on the critical path, and therefore, `timeoutPropose` would need to be updated accordingly. One idea would be allowing application to provide some hint to the Tendermint regarding duration of `PrepareProposal` so the `timeoutPropose` could be estimated more correctly (https://github.com/tendermint/spec/pull/327/files#r711591018).
- I would suggest storing the result of `ABCI.ProcessProposal` in a local variable and using it at line 52, as this presentation might suggest two ABCI calls (https://github.com/tendermint/spec/pull/327/files#r711591437)
- Clarify benefits of evidence handling as part of ABCI processing logic (https://github.com/tendermint/spec/pull/327/files#r711591744)
- We need also precommit_extension field as part of PRECOMMIT message (https://github.com/tendermint/spec/pull/327/files#r711592538)
- From semantic perspective this presentation is not ideal as upon rules are atomic, so blocking within upon rule prevents any other rule being triggered. If we want to separate sending/receiving proposal_header from the proposal_data, we should probably introduce two message types (https://github.com/tendermint/spec/pull/327/files#r711593978)
- PROPOSAL message contains full block proposal in this rule, while above it is only header. As mentioned above, we can make it clear by having in addition to PROPOSAL, also PROPOSAL_HEADER message and then have a separate rule for PROPOSAL_HEADER message (https://github.com/tendermint/spec/pull/327/files#r711594462).
- I would prefer using slightly different semantics to signal it is asynchronous computation: we can distinct between synchronous ABCI calls where we are synchronously waiting for result, or asynchronous where we are essentially sending a request and will receive reply later (eventually). I don't have strong preference how we can capture this, maybe using Future or Promise as a return value. Then instead of Join we can have upon rule contains condition based on response. The benefit is that there is no blocking wait inside the upon rule as it semantically prevents other upon rules being triggered (https://github.com/tendermint/spec/pull/327/files#r711618984)
- Clarify the semantics of Join (https://github.com/tendermint/spec/pull/327/files#r711619497).

**Comment by sergio-mena** [comment]
After merging #366, the only remaining comment to be addressed in this issue is:

* We need also precommit_extension field as part of PRECOMMIT message (https://github.com/tendermint/spec/pull/327/files#r711592538)

The rest of them have either been addressed or become obsolete in the new spec write-up introduced in #366

**Comment by cmwaters** [comment]
I think after the discussions around Vote Extensions, we've resolved all outstanding comments that were brought up by Zarko. I'm going to go ahead and close this unless someone has more they would like to bring up
