### ISSUE TITLE
abci: update proto's to reflect changes in ABCI++ 

### ISSUE THREAD

**Issue by cmwaters** [tendermint/spec#386]
## Summary

The changes to the application interface described in https://github.com/tendermint/spec/pull/366 needs to be ported across to the proto definitions.

NOTE: we should first tag a snapshot of the protobuf definitions of v0.35 and create a long lived branch in the event that a minor release updates them.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by sergio-mena** [comment]
Addressed via #392
