### ISSUE TITLE
Difference between 2f+1 and 2n/3

### ISSUE THREAD

**Issue by DontMont** [tendermint/spec#45]
I've seen literature related to the tendermint protocol where the requirement of 2f+1 votes or 2n/3 votes or +2/3 votes is used interchangeably. 
please, can this be confirmed that if these formulae are indeed used interchangeably or if there is really a difference? i.e. when implemented is there any real difference between 2f+1 or 2n/3?

**Comment by milosevic** [comment]
2f+1 is used as a quorum size in case we fix total voting power to n = 3f+1. This is normally done in case of proofs as a simplification as it does not effect complexity of proofs but simplifies presentation a bit.
 In a general case (when n > 3f), the quorum size is +2n/3. I hope this answer to your question. So in the implementation you probably want to use  +2n/3 as a quorum size.
