### ISSUE TITLE
higher rounds change discrepancy between spec and implementation

### ISSUE THREAD

**Issue by aneequesafdar** [tendermint/spec#46]
@aesmonty @yazzaoui, @JekaMas and I have been studying and implementing Tendermint based on [this](https://arxiv.org/pdf/1807.04938.pdf) specification and we felt there is a vulnerability on `L55`, where a byzantine node can cause constant round change for an honest node by sending prevote and precommit.

For example, in a network of 4 nodes with one byzantine node, thus `F = 1 and F+1 = 2` and based on the condition of round change on `L55` the byzantine node can send a precommit and prevote of any kind and satisfy `f + 1 <∗, hp, round, ∗, ∗>`, cause infinite round changes in one honest node, since the other honest node depend on this node, it will break liveness.

We investigated the Tendermint repo and in the documentation, you have mentioned completely different [exit conditions](https://github.com/tendermint/tendermint/blob/master/docs/spec/consensus/consensus.md#common-exit-conditions) condition to change to higher rounds, where in order to move to a higher round the honest nodes need 2F+1 prevotes or precommits, which is a must stronger condition than F+1 message of any kind from a higher round.

Can you please explain which one is correct and which one should we implement?

**Comment by ebuchman** [comment]
> the byzantine node can send a precommit and prevote of any kind and satisfy f + 1 `<∗, hp, round, ∗, ∗>`

Can you clarify how a single Byzantine node would cause this condition to be satisfied? `f+1` implies "at least one correct node". So I believe the idea here is that if we can guarantee we got a message from `round` from at least one correct node than we can skip to that round cc @milosevic @josef-widder 

It's possible the implementation is using an unnecessarily strong condition though. We'll look into it.

**Comment by josef-widder** [comment]
`upon f + 1 (∗, h_p, round, ∗, ∗) with round > round_p do` should be understood as "upon receiving `(∗, h_p, round, ∗, ∗)` from *f + 1* distinct nodes". Hence one faulty process sending 2 messages cannot trigger that event.

**Comment by aneequesafdar** [comment]
@ebuchman 
> Can you clarify how a single Byzantine node would cause this condition to be satisfied? f+1 implies "at least one correct node".

We understand the intention behind having at least`f+1` future messages, however, it was unclear to us what was meant by `<∗, hp, round, ∗, ∗>` because this type can be satisfied by a proposal, prevote or precommit message. Leading to the confusion that if a byzantine node is the proposer for some future round it can send 3 correct messages: a proposal, prevote and precommit for a value.

From a correct node's perspective, these messages are well-formed and valid so do these messages separately count toward the total for `f+1`? If so, then than means in a network of 4 a byzantine node can fulfil the at least `f+1 <∗, hp, round, ∗, ∗>` requirment by sending a prevote and precommit messages for some value from a future round as `f+1 == 2` (in this case).

We believed this to be problematic and can lead to liveness issues, thus we also interpreted it as @josef-widder mentioned (however, we needed clarification)
> "upon receiving (∗, h_p, round, ∗, ∗) from f + 1 distinct nodes"

Where a prevote and precommit from the same sender will not be counted twice toward the total for `f+1`, thus, ensuring a byzantine node alone cannot cause a round change for a correct process in the scenario mentioned above.

**Comment by ebuchman** [comment]
That's right, the f+1 implies distinct senders, not just distinct messages. You're right this is a bit ambiguous and should be clarified, thanks!

**Comment by milosevic** [comment]
Please check these sentences from the section III: "An upon rule is
triggered once the message log contains messages such that the corresponding condition evaluates to true.
The condition that assumes reception of X messages of a particular type and content denotes reception of
messages whose senders have aggregate voting power at least equal to X. For example, the condition 2f + 1
<PRECOMMIT, hp, r, id(v)>, evaluates to true upon reception of PRECOMMIT messages for height hp, a round
r and with value equal to id(v) whose senders have aggregate voting power at least equal to 2f + 1." The condition at line 55 therefore implies reception of any kind of messages for round r > rp such that total voting power is at least f+1. Therefore, having multiple messages from the same sender counts only once.
