### ISSUE TITLE
update spec link & re-organize sidebar

### ISSUE THREAD

**Issue by milosevic** [tendermint/spec#66]
This state machine diagram is outdated and source of confusion: https://github.com/tendermint/tendermint/blob/develop/docs/spec/consensus/consensus.md#state-machine-spec. Could we replace it with a pointer to a spec repo https://github.com/tendermint/spec?

**Comment by marbar3778** [comment]
@milosevic let me know if this is still relevent

**Comment by marbar3778** [comment]
Closing this as the spec repo is now viewed under docs.tendermint.com.
