### ISSUE TITLE
Document ABCI as a Protobuf interface instead of a Go interface

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/spec#89]
The ABCI spec currently uses field names and data types from the Go interface rather than the Protobuf interface (e.g. `AppHash` instead of `app_hash`, and `[]byte` instead of `bytes`). If we want ABCI to be an implementation-agnostic protocol, perhaps the spec should document the Protobuf interface instead?

**Comment by alexanderbez** [comment]
I'm in favor of such a change.

**Comment by marbar3778** [comment]
I am in favor of this. To add to this I would also do all the reactors and type representations we have in go. If they are in proto, which they should be.

**Comment by marbar3778** [comment]
I'll take this on.
