### ISSUE TITLE
ABCI documentation order

### ISSUE THREAD

**Issue by hxrts** [tendermint/spec#98]
when on [this documentation page](https://docs.tendermint.com/master/spec/abci/client-server.html) the intro says "You are expected to have read ABCI Methods and Types and ABCI Applications." which are sequentially later in the documentation navigation.

Then when I click the "fix on github button" it brings me to the wrong page, the correct link should be:

https://github.com/tendermint/spec/blob/master/spec/abci/client-server.md

instead of the following:

https://github.com/tendermint/tendermint/edit/master/docs/spec/abci/client-server.md

**Comment by ebuchman** [comment]
@hxrts is this still relevant or can we close? the links from `You are expected to have read ABCI Methods and Types and ABCI Applications."` seem to work and I don't see the "fix on github button" anymore

**Comment by hxrts** [comment]
yep!
